import { useState } from 'react';
import { Link } from '@tanstack/react-router';
import { ArrowUpRight, TriangleAlert, CircleAlert, CheckCheck, Check, Eye, Clock } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { useCommand } from './store';
import { Badge, Modal, Panel } from './shared';
import type { SafetyAlert } from '@/lib/monitoring-api';
export function AlertDetail({ alert, onClose }: { alert:SafetyAlert;onClose:()=>void }) { const { updateAlert } = useCommand(); return <Modal title={`Alert details · ${alert.id}`} onClose={onClose}><Badge tone={alert.severity.toLowerCase()}>{alert.severity}</Badge><h3 className="mt-5 text-lg">Capacity threshold exceeded in {alert.zone}</h3><p className="mt-2 text-muted-foreground">{alert.people} people were detected in a zone configured for {alert.capacity}. Occupancy reached {alert.occupancy}%.</p><dl className="detail-grid"><div><dt>Camera</dt><dd>Testing Webcam</dd></div><div><dt>Location</dt><dd>Main concourse</dd></div><div><dt>Detected at</dt><dd>06 Oct 2026 · {alert.time} UTC</dd></div><div><dt>Status</dt><dd>{alert.status}</dd></div></dl><h3 className="mb-3 font-medium">Event history</h3><ul className="event-history">{alert.history.map(h => <li key={h}><Clock size={13} />{h}</li>)}</ul><div className="modal-actions"><Button variant="outline" disabled={alert.status !== 'Active'} onClick={() => updateAlert(alert.id,'Acknowledged')}><Check />Acknowledge</Button><Button disabled={alert.status === 'Resolved'} onClick={() => updateAlert(alert.id,'Resolved')}><CheckCheck />Resolve alert</Button></div></Modal>; }
export function RecentAlerts() { const { alerts,updateAlert } = useCommand(); const [id,setId] = useState<string|null>(null); const selected = alerts.find(a => a.id === id); return <><Panel title="Recent alerts" extra={<Button variant="link" size="sm" asChild><Link to="/alerts">View all <ArrowUpRight size={13} /></Link></Button>}><div className="recent-alerts">{alerts.slice(0,3).map(a => <article className={`recent-alert tone-${a.severity.toLowerCase()} ${a.status === 'Resolved' ? 'alert-resolved' : ''}`} key={a.id}><div className="alert-icon">{a.severity === 'Critical' ? <TriangleAlert size={18} /> : <CircleAlert size={18} />}</div><div className="alert-body"><div><strong>{a.zone} · {a.severity === 'Critical' ? 'Capacity exceeded' : 'High occupancy'}</strong><time>{a.time.slice(0,5)}</time></div><p>{a.occupancy}% occupancy <span>·</span> Testing Webcam</p><div className="alert-actions"><Badge tone={a.status === 'Resolved' ? 'muted' : a.severity.toLowerCase()}>{a.status}</Badge><Button variant="ghost" size="sm" onClick={() => setId(a.id)}>View</Button>{a.status !== 'Resolved' && <Button variant="ghost" size="sm" onClick={() => updateAlert(a.id,a.status === 'Active' ? 'Acknowledged' : 'Resolved')}>{a.status === 'Active' ? 'Acknowledge' : 'Resolve'}</Button>}</div></div></article>)}</div></Panel>{selected && <AlertDetail alert={selected} onClose={() => setId(null)} />}</>; }
export function AlertTable({ filter }: { filter:string }) { const { alerts,updateAlert } = useCommand(); const [id,setId] = useState<string|null>(null); const selected = alerts.find(a => a.id === id); const rows = alerts.filter(a => filter === 'All' || a.severity === filter || a.status === filter); return <><div className="table-scroll"><table><thead><tr>{['Alert ID','Severity','Camera / Zone','People','Occupancy','Created at','Status','Actions'].map(h => <th key={h}>{h}</th>)}</tr></thead><tbody>{rows.map(a => <tr key={a.id}><td className="font-mono">{a.id}</td><td><Badge tone={a.severity.toLowerCase()}>{a.severity}</Badge></td><td>Testing Webcam<small>{a.zone}</small></td><td>{a.people} / {a.capacity}</td><td className={`text-${a.severity === 'Critical' ? 'destructive' : 'warning'}`}>{a.occupancy}%</td><td>{a.time}<small>06 Oct 2026</small></td><td><Badge tone={a.status === 'Resolved' ? 'normal' : 'muted'}>{a.status}</Badge></td><td><div className="flex gap-1"><Button variant="ghost" size="icon" title="View details" aria-label={`View ${a.id}`} onClick={() => setId(a.id)}><Eye /></Button><Button variant="ghost" size="icon" title="Acknowledge" aria-label={`Acknowledge ${a.id}`} disabled={a.status !== 'Active'} onClick={() => updateAlert(a.id,'Acknowledged')}><Check /></Button><Button variant="ghost" size="icon" title="Resolve" aria-label={`Resolve ${a.id}`} disabled={a.status === 'Resolved'} onClick={() => updateAlert(a.id,'Resolved')}><CheckCheck /></Button></div></td></tr>)}</tbody></table>{rows.length === 0 && <div className="empty-state"><CheckCheck />No matching alerts</div>}</div>{selected && <AlertDetail alert={selected} onClose={() => setId(null)} />}</>; }
