import { useRef, useState } from 'react';
import { Maximize, ScanLine, Video, Layers, Pause, Play, Square } from 'lucide-react';
import station from '@/assets/station-feed.jpg';
import { Button } from '@/components/ui/button';
import { useCommand } from './store';
import { Badge } from './shared';
const boxes = [{ x: 14, y: 66, w: 7, h: 28 }, { x: 27, y: 44, w: 5, h: 19 }, { x: 35, y: 39, w: 4, h: 17 }, { x: 41, y: 34, w: 4, h: 17 }, { x: 47, y: 64, w: 6, h: 28 }, { x: 61, y: 42, w: 5, h: 20 }, { x: 64, y: 65, w: 6, h: 27 }, { x: 70, y: 39, w: 5, h: 20 }, { x: 74, y: 44, w: 4, h: 17 }, { x: 78, y: 43, w: 5, h: 19 }, { x: 86, y: 63, w: 6, h: 24 }, { x: 88, y: 45, w: 5, h: 17 }];
export function CameraSelector() { const { cameras, selectedCamera, setSelectedCamera } = useCommand(); return <select aria-label="Select camera" value={selectedCamera} onChange={e => setSelectedCamera(e.target.value)}>{cameras.map(c => <option key={c.id} value={c.id}>{c.name}</option>)}</select>; }
export function Feed({ large = false }: { large?: boolean }) {
 const { cameras, selectedCamera, zones, monitoring, setMonitoring, notify } = useCommand();
 const [overlays, setOverlays] = useState(true);
 const container = useRef<HTMLDivElement>(null);
 const camera = cameras.find(c => c.id === selectedCamera);
 const online = camera?.status === 'Online';
 const fullscreen = async () => { try { if (document.fullscreenElement) await document.exitFullscreen(); else await container.current?.requestFullscreen(); } catch { notify('Fullscreen is unavailable in this preview.'); } };
 return <div className={`feed-container ${large ? 'feed-large' : ''}`} ref={container}><div className="feed-top"><div className="flex items-center gap-2"><Video size={16} /><strong>{camera?.name ?? 'No camera selected'}</strong><Badge tone={online && monitoring === 'Running' ? 'normal' : 'muted'}>{online ? monitoring === 'Running' ? 'LIVE · DEMO' : monitoring.toUpperCase() : 'STANDBY'}</Badge></div><div className="feed-tools"><Button size="icon" variant="ghost" title="Toggle detection overlays" aria-label="Toggle detection overlays" onClick={() => setOverlays(v => !v)}><Layers /></Button><Button size="icon" variant="ghost" title="Fullscreen" aria-label="Fullscreen" onClick={fullscreen}><Maximize /></Button></div></div><div className="camera-image"><img src={station} alt="Simulated surveillance view of a railway station concourse" width={1536} height={864} />{online && monitoring !== 'Stopped' ? <><div className="feed-stamp">CAM 01 <span>OCT 06 2026 · 14:42:16 UTC</span></div>{overlays && <><div className="detection-zones">{zones.map(z => <div key={z.id} className={`detection-zone zone-${z.id.toLowerCase()}`}><span>{z.name.toUpperCase()} <b>{z.people} PEOPLE</b></span></div>)}</div>{boxes.map((b, i) => <div key={i} className={`person-box ${b.x > 65 ? 'person-critical' : ''}`} style={{ left: `${b.x}%`, top: `${b.y}%`, width: `${b.w}%`, height: `${b.h}%` }}><span>ID {String(101 + i)}</span></div>)}</>}{monitoring === 'Paused' && <div className="feed-state"><Pause />Monitoring paused</div>}<div className="feed-watermark"><ScanLine size={14} /> YOLO PERSON DETECTION <span>SIMULATED FEED</span></div></> : <div className="feed-state"><Video size={30} /><h3>{online ? 'Monitoring stopped' : 'Camera not connected'}</h3><p>{online ? 'Ready to start a demonstration session' : 'Awaiting a future camera stream'}</p></div>}</div><div className="feed-bottom"><span className="flex items-center gap-2"><span className="status-dot text-normal" />{online ? 'Sample stream' : 'No stream'}<span className="divider" />{online ? '1920 × 1080' : '—'}</span><span>{online && monitoring === 'Running' ? '24' : '0'} FPS <span className="divider" /> <ScanLine size={13} /> {zones.reduce((s,z) => s + (z.enabled ? z.people : 0),0)} people</span></div></div>;
}
export function MonitoringControls() { const { monitoring, setMonitoring, cameras, selectedCamera } = useCommand(); const online = cameras.find(c => c.id === selectedCamera)?.status === 'Online'; return <div className="flex flex-wrap gap-2"><Button disabled={!online || monitoring === 'Running'} onClick={() => setMonitoring('Running')}><Play />{monitoring === 'Paused' ? 'Resume' : 'Start Monitoring'}</Button><Button variant="outline" disabled={!online || monitoring !== 'Running'} onClick={() => setMonitoring('Paused')}><Pause />Pause</Button><Button variant="outline" disabled={!online || monitoring === 'Stopped'} onClick={() => setMonitoring('Stopped')}><Square />Stop</Button></div>; }
