import type { ReactNode } from 'react';
import { X, ArrowUpRight, Camera, Users, BellRing, ShieldAlert } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { useCommand } from './store';
import { zoneStatus, type Zone } from '@/lib/monitoring-api';
export function Badge({ children, tone = 'muted' }: { children: ReactNode; tone?: string }) { return <span className={`status-badge tone-${tone}`}><span className="status-dot" />{children}</span>; }
export function PageHeading({ eyebrow = 'SECURITY OPERATIONS', title, subtitle, children }: { eyebrow?: string; title: string; subtitle: string; children?: ReactNode }) { return <div className="page-heading"><div><div className="eyebrow">{eyebrow}</div><h1>{title}</h1><p>{subtitle}</p></div><div className="heading-actions">{children}</div></div>; }
export function Panel({ title, extra, children, className = '' }: { title: string; extra?: ReactNode; children: ReactNode; className?: string }) { return <section className={`panel ${className}`}><header className="panel-heading"><h2>{title}</h2>{extra}</header>{children}</section>; }
export function Modal({ title, children, onClose }: { title: string; children: ReactNode; onClose: () => void }) { return <div className="modal-backdrop" onClick={onClose}><section role="dialog" aria-modal="true" aria-label={title} className="modal" onClick={e => e.stopPropagation()}><header className="panel-heading"><h2>{title}</h2><Button variant="ghost" size="icon" aria-label="Close dialog" onClick={onClose}><X /></Button></header><div className="modal-body">{children}</div></section></div>; }
export function Stats() {
 const { cameras, zones, alerts } = useCommand();
 const items = [{ label: 'ACTIVE CAMERAS', value: cameras.filter(c => c.status === 'Online').length.toString().padStart(2, '0'), caption: `${cameras.length} cameras configured`, icon: Camera, tone: 'primary', note: 'Online' }, { label: 'PEOPLE DETECTED', value: zones.filter(z => z.enabled).reduce((n, z) => n + z.people, 0), caption: 'Across all monitored zones', icon: Users, tone: 'primary', note: 'Live count' }, { label: 'ACTIVE ALERTS', value: alerts.filter(a => a.status !== 'Resolved').length.toString().padStart(2, '0'), caption: 'Requires operator attention', icon: BellRing, tone: 'warning', note: 'Attention' }, { label: 'CRITICAL ZONES', value: zones.filter(z => zoneStatus(z) === 'Critical').length.toString().padStart(2, '0'), caption: 'Above configured capacity', icon: ShieldAlert, tone: 'destructive', note: 'High risk' }];
 return <div className="stats-grid">{items.map(item => <article className={`stat-card tone-${item.tone}`} key={item.label}><div className="stat-top"><span>{item.label}</span><item.icon size={19} /></div><div className="stat-value">{item.value}<span className="stat-note"><span className="status-dot" />{item.note}</span></div><div className="stat-bottom"><span>{item.caption}</span><ArrowUpRight size={15} /></div></article>)}</div>;
}
export function ZoneCards() { const { zones } = useCommand(); return <div className="zone-cards">{zones.map(z => <ZoneCard key={z.id} zone={z} />)}</div>; }
function ZoneCard({ zone }: { zone: Zone }) { const status = zoneStatus(zone); const percent = Math.round(zone.people / zone.capacity * 100); return <article className={`zone-card tone-${status.toLowerCase()}`}><div className="flex items-center justify-between"><h3><span className="zone-letter">{zone.id}</span>{zone.name}</h3><Badge tone={status.toLowerCase()}>{status}</Badge></div><div className="zone-numbers"><strong>{zone.people}<span> / {zone.capacity}</span></strong><span>{percent}% <small>occupancy</small></span></div><progress max={100} value={zone.enabled ? Math.min(100, percent) : 0} /><p>{status === 'Critical' ? `${zone.people - zone.capacity} people above capacity` : status === 'Warning' ? 'Approaching maximum capacity' : status === 'Disabled' ? 'Monitoring disabled' : 'Within safe capacity'}</p></article>; }
